### ISSUE TITLE
Ability to configure authorized ssh keys

### ISSUE THREAD

**Issue by krzysztof-magosa** [vagrant-dotvm/vagrant-dotvm#1]
It would be nice to have ability to add predefined authorized ssh keys from files.

**Comment by krzysztof-magosa** [comment]
Possible since 0.11.0.

```
authorized_keys:
  - type: file
    path: "%project.host%/shared_id_rsa.pub"
  - type: static
    key: "pub key here"
```
