### ISSUE TITLE
Support for third party plugins

### ISSUE THREAD

**Issue by jhcook** [vagrant-dotvm/vagrant-dotvm#41]
I'm not sure what the easiest way would be to do this, but since we are abstracting Vagrant's interface with YAML, we need to be able to support third-party plugins. Tonight I was working on a situation where I needed to reload between provisioners. I added on a plugin called vagrant-reload by `vagrant plugin install vagrant-reload` and place this snippet in the yaml file:

```
provision:
    - type: shell
      inline: "atomic host upgrade"
    - type: shell
      path: "%host.files_dir%/k8smaster_provision.sh"
    - type: reload
    - type: shell
      path: "%host.files_dir%/k8smaster_provision2.sh"
```

and get the error on `vagrant up`:

```
==> k8smaster: Running provisioner: shell...
    k8smaster: Running: /var/folders/7l/nmm2h83x0l1c341q9jkm03xw0000gn/T/vagrant-shell20160306-10088-4rzt1b.sh
==> k8smaster: unknown
```

https://github.com/aidanns/vagrant-reload

**Comment by jhcook** [comment]
So while I since figured out I was colliding "shell" keys, I corrected that part. But, how would one execute a shell, then another provisioner, and then another shell?

```
  provision:
    - type: shell
      path: "%host.files_dir%/k8smaster_provision.sh"
    - type: shell
      path: "%host.files_dir%/k8smaster_provision2.sh"
```

The reload should go between the two.
