### ISSUE TITLE
vagrant-service-manager plugin introduces abnormal behaviour

### ISSUE THREAD

**Issue by jhcook** [vagrant-dotvm/vagrant-dotvm#45]
I noticed some strange behaviour in the not-so-distant past after installing vagrant-service-manager. So, I uninstalled it, and things returned to normal. 

However, the project I am working on is using vagrant-service-manager as well as vagrant-dotvm, so it needs to be rectified. The problem is with interfaces. The following configuration snippet is used:

Variable in another file:

```
interface: vboxnet0
```

Part of machine definition:

```
natnet: "%global.natnet%"
  networks:
  - net: private_network
    type: static
    ip: 10.100.1.11
    netmask: 255.255.255.0
    interface: "%project.interface%"
```

When the machine comes up in VirtualBox, there interface one is the usual NAT network. Interface two is vboxnet1 with a 172.28.128.x address. Interface three is the correct network, or vboxnet0.

Removing vagrant-service-manager plugin removes this behaviour.
