### ISSUE TITLE
Interface not enabled on provision with Vagrant 1.9.1

### ISSUE THREAD

**Issue by jhcook** [vagrant-dotvm/vagrant-dotvm#47]
Vagrant images in Virtualbox with a private network on eth1 are configured, but not enabled when the box is brought up. 

YAML for a machine definition is:
```
  networks:
    - net: private_network
      type: static
      ip: 10.100.100.12
      mask: 255.255.0.0
      interface: "%project.interface%"
```

The following is to edit the ifcfg and change `NM_CONTROLLED=yes`, reload the connections and the connection is then enabled.

```
[vagrant@ukbeisipa02 ~]$ sudo vi /etc/sysconfig/network-scripts/ifcfg-eth1
[vagrant@ukbeisipa02 ~]$ sudo nmcli connection reload
[vagrant@ukbeisipa02 ~]$ nmcli con show
NAME         UUID                                  TYPE            DEVICE
System eth1  9c92fad9-6ecb-3e6c-eb4d-8a47c6f50c04  802-3-ethernet  eth1
eth0         be63cb9d-2ef1-449b-9975-d896095178f9  802-3-ethernet  eth0
[vagrant@ukbeisipa02 ~]$ ip addr show dev eth1
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:1a:5d:1b brd ff:ff:ff:ff:ff:ff
    inet 10.100.100.12/16 brd 10.100.255.255 scope global eth1
...
```

**Comment by jhcook** [comment]
This is the issue:

https://github.com/mitchellh/vagrant/issues/6975

**Comment by jhcook** [comment]
This is a workaround in vagrant-dotvm:
```
provision:
    - type: shell
      inline: "ifup eth1"
      run: always
```
