### ISSUE TITLE
ssh array of hashes

### ISSUE THREAD

**Issue by jhcook** [vagrant-dotvm/vagrant-dotvm#5]
Currenty, "authorized_keys" is an array of hash entries for public keys to populate ~/.ssh/authorized_keys. While this is good, it would be nice to have an array consisting of all ssh data such as:

``` yaml
machines:
  - name: some_machine
    ...
    ssh:
      - private_keys:
        - type: file
          path: "~/.ssh/id_rsa"
        public_keys:
        - type: file
          path: "~/.ssh/id_rsa.pub"
        authorized_keys:
        - type: file
          path: "~/.ssh/id_rsa.pub"
    ...
```

This way, you could be explicit with each guest (machine) on which keys to populate and which keys to trust.

**Comment by krzysztof-magosa** [comment]
I agree, we could also have ssh options there, so everything related with SSH would be centralized in one branch in YAML.

``` yaml
machines:
  - name: some_machine
    ...
    ssh:
      - options:
        user: "vagrant" 
      - private_keys:
        - type: file
          path: "~/.ssh/id_rsa"
        public_keys:
        - type: file
          path: "~/.ssh/id_rsa.pub"
        authorized_keys:
        - type: file
          path: "~/.ssh/id_rsa.pub"
    ...
```
